name: .NET

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  welcome:
    runs-on: windows-latest
    
    steps:
      - name: Welcome message
        run: echo "Welcome!"
